import {
  AndroidConfig,
  ConfigPlugin,
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
  withGradleProperties,
} from "expo/config-plugins";
import fs from "fs";
import path from "path";

/**
 * Everything in this file exists so that `expo prebuild --clean` can regenerate
 * android/ from scratch without losing the release configuration. The generated
 * project is still committed, but it is now reproducible rather than hand-edited.
 */

const APPLY_LINE = `apply from: "$projectDir/maid-build.gradle"`;

/**
 * Release build configuration: version naming, keystore selection and ABI splits.
 *
 * Lives in its own Gradle script rather than being spliced into the generated
 * app/build.gradle so that an SDK upgrade can rewrite the template freely. A
 * script applied from within :app can still configure `android { }`, so nothing
 * here needs to be injected inline.
 */
const MAID_BUILD_GRADLE = `// @generated by plugins/with-maid-android.ts - do not edit directly.
//
// Release configuration for Google Play and F-Droid:
//   * versionName comes from package.json
//   * versionCode comes from the git commit count, leaving room for per-ABI offsets
//   * AAB builds sign with the upload key, APK builds sign with the release key
//   * APK builds are split per ABI, plus a universal APK

def versionNameFromPkg = "1.0.0"
try {
    versionNameFromPkg = ["node", "--print", "require('../package.json').version"]
            .execute(null, rootDir)
            .text
            .trim()
} catch (Throwable t) {
    println("⚠️ Could not read package.json version, using \${versionNameFromPkg}")
}

// Multiplied by 10 so each ABI can claim its own offset below without colliding
// with the next commit's version code.
def versionCodeFromGit = 1
try {
    versionCodeFromGit = ["git", "rev-list", "--count", "HEAD"]
            .execute(null, rootDir)
            .text
            .trim()
            .toInteger() * 10
} catch (Throwable t) {
    println("⚠️ Could not read git commit count, using \${versionCodeFromGit}")
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

// Play Store artifacts are AABs, which must be signed with the upload key.
def isBundleBuild = project.gradle.startParameter.taskNames.any { it.toLowerCase().contains("bundle") }

android {
    defaultConfig {
        versionCode versionCodeFromGit
        versionName versionNameFromPkg

        if (isBundleBuild) {
            ndk {
                abiFilters 'x86_64', 'arm64-v8a'
            }
        }
    }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }

        upload {
            if (keystorePropertiesFile.exists()
                    && keystoreProperties['uploadKey']
                    && keystoreProperties['storePassword']
                    && keystoreProperties['uploadAlias']
                    && keystoreProperties['uploadPassword']) {

                storeFile file(keystoreProperties['uploadKey'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['uploadAlias']
                keyPassword keystoreProperties['uploadPassword']
            } else {
                println("⚠️ Keystore properties not found or incomplete; upload builds will use debug signing unless you add key.properties.")
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }

        release {
            if (keystorePropertiesFile.exists()
                    && keystoreProperties['signingKey']
                    && keystoreProperties['storePassword']
                    && keystoreProperties['releaseAlias']
                    && keystoreProperties['releasePassword']) {

                storeFile file(keystoreProperties['signingKey'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['releaseAlias']
                keyPassword keystoreProperties['releasePassword']
            } else {
                println("⚠️ Keystore properties not found or incomplete; release builds will use debug signing unless you add key.properties.")
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            versionNameSuffix "-debug"
        }

        release {
            signingConfig isBundleBuild
                    ? signingConfigs.upload
                    : signingConfigs.release
        }
    }

    splits {
        abi {
            // AGP refuses to build an app bundle while per-ABI APK splits are on
            // (https://issuetracker.google.com/402800800): resource shrinking
            // produces one shrunk-resources file per split and the bundle task
            // cannot pick between them. The AAB does not need splits anyway -
            // Play splits it per device, and \`abiFilters\` above already limits
            // it to the two ABIs we ship.
            enable !isBundleBuild
            reset()
            include 'x86_64', 'arm64-v8a'
            exclude 'armeabi-v7a'
            universalApk true
        }
    }
}

// Play requires every APK in a multi-APK release to carry a distinct version code.
android.applicationVariants.all { variant ->
    variant.outputs.each { output ->
        // The literal rather than \`com.android.build.OutputFile.ABI\`: an applied
        // script cannot resolve AGP classes at script-compile time, and the
        // constant is just this string.
        def abi = output.getFilter("ABI")
        if (abi != null) {
            def abiCodes = [
                "arm64-v8a": 1,
                "x86_64"   : 2,
            ]

            output.versionCodeOverride =
                versionCodeFromGit + (abiCodes.get(abi) ?: 0)
        }
    }
}
`;

/**
 * Allows plain-HTTP traffic so the app can reach a local Ollama server, and
 * trusts user-installed CAs in debug builds for proxy inspection.
 */
const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system"/>
    </trust-anchors>
  </base-config>
  <debug-overrides>
    <trust-anchors>
      <certificates src="system"/>
      <certificates src="user"/>
    </trust-anchors>
  </debug-overrides>
</network-security-config>
`;

/**
 * Release builds run R8 *and* resource shrinking, so these keeps are load
 * bearing - without them the reanimated/worklets and llama.rn JNI entry points
 * are stripped.
 */
const PROGUARD_RULES = `# @generated by plugins/with-maid-android.ts - do not edit directly.

# react-native-reanimated / react-native-worklets
-keep class com.swmansion.reanimated.** { *; }
-keep class com.swmansion.worklets.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# llama.rn
-keep class com.rnllama.** { *; }
`;

const GRADLE_PROPERTIES: Record<string, string> = {
  // Only ship the two ABIs we actually support.
  reactNativeArchitectures: "arm64-v8a,x86_64",
  // The default 2g heap intermittently fails `packageRelease` while zipping the
  // ~190 MB universal APK alongside the per-ABI ones.
  "org.gradle.jvmargs": "-Xmx4096m -XX:MaxMetaspaceSize=512m",
  // SDK 56 renamed `android.enableProguardInReleaseBuilds` to this. Resource
  // shrinking is an AGP error unless code shrinking is on too, so they move
  // together.
  "android.enableMinifyInReleaseBuilds": "true",
  "android.enableShrinkResourcesInReleaseBuilds": "true",
  "android.enablePngCrunchInReleaseBuilds": "true",
  "expo.gif.enabled": "true",
  "expo.webp.enabled": "true",
  EX_DEV_CLIENT_NETWORK_INSPECTOR: "true",
};

/**
 * Build outputs that land inside the committed android/ tree. Appended to the
 * generated .gitignore, which prebuild rewrites from the template each time.
 */
const GIT_IGNORE_MARKER = "# @generated by plugins/with-maid-android.ts";
const GIT_IGNORE_ENTRIES = [
  GIT_IGNORE_MARKER,
  "",
  "# Kotlin Gradle plugin session files",
  ".kotlin/",
  "",
  "# JS bundle and llama.rn Hexagon binaries, both emitted by the release build",
  "app/src/main/assets/",
];

const writeAndroidFile = (
  projectRoot: string,
  relativePath: string,
  contents: string,
) => {
  const target = path.join(projectRoot, "android", relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents);
};

const withMaidBuildGradle: ConfigPlugin = (config) => {
  config = withDangerousMod(config, [
    "android",
    (config) => {
      writeAndroidFile(
        config.modRequest.projectRoot,
        "app/maid-build.gradle",
        MAID_BUILD_GRADLE,
      );
      return config;
    },
  ]);

  return withAppBuildGradle(config, (config) => {
    if (!config.modResults.contents.includes(APPLY_LINE)) {
      config.modResults.contents += `\n${APPLY_LINE}\n`;
    }
    return config;
  });
};

const withNetworkSecurityConfig: ConfigPlugin = (config) => {
  config = withDangerousMod(config, [
    "android",
    (config) => {
      writeAndroidFile(
        config.modRequest.projectRoot,
        "app/src/main/res/xml/network_security_config.xml",
        NETWORK_SECURITY_CONFIG,
      );
      return config;
    },
  ]);

  return withAndroidManifest(config, (config) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(
      config.modResults,
    );
    application.$["android:networkSecurityConfig"] =
      "@xml/network_security_config";
    return config;
  });
};

const withProguardRules: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      writeAndroidFile(
        config.modRequest.projectRoot,
        "app/proguard-rules.pro",
        PROGUARD_RULES,
      );
      return config;
    },
  ]);

const withMaidGitIgnore: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const target = path.join(
        config.modRequest.projectRoot,
        "android",
        ".gitignore",
      );
      const contents = fs.readFileSync(target, "utf8");

      if (contents.includes(GIT_IGNORE_MARKER)) {
        return config;
      }

      fs.writeFileSync(
        target,
        `${contents.trimEnd()}\n\n${GIT_IGNORE_ENTRIES.join("\n")}\n`,
      );
      return config;
    },
  ]);

const withMaidGradleProperties: ConfigPlugin = (config) =>
  withGradleProperties(config, (config) => {
    for (const [key, value] of Object.entries(GRADLE_PROPERTIES)) {
      const existing = config.modResults.find(
        (item) => item.type === "property" && item.key === key,
      );

      if (existing && existing.type === "property") {
        existing.value = value;
      } else {
        config.modResults.push({ type: "property", key, value });
      }
    }
    return config;
  });

const withMaidAndroid: ConfigPlugin = (config) => {
  config = withMaidBuildGradle(config);
  config = withNetworkSecurityConfig(config);
  config = withProguardRules(config);
  config = withMaidGradleProperties(config);
  config = withMaidGitIgnore(config);
  return config;
};

export default withMaidAndroid;
