// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuj3iW2uEmkbIyjboZQXLkOrYtZEoZ50M',
    appId: '1:721822016477:web:dbae67d9e033a5b0b78c34',
    messagingSenderId: '721822016477',
    projectId: 'mobile-ai-distribution',
    authDomain: 'mobile-ai-distribution.firebaseapp.com',
    storageBucket: 'mobile-ai-distribution.firebasestorage.app',
    measurementId: 'G-GH549YPLKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOlhLILnUfxFWAfMYNgdSuzPUQ38T3cqY',
    appId: '1:721822016477:android:7205e0ee57c9d295b78c34',
    messagingSenderId: '721822016477',
    projectId: 'mobile-ai-distribution',
    storageBucket: 'mobile-ai-distribution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5c7-uyIcP9V_Em29heke4cLBTqA-56XE',
    appId: '1:721822016477:ios:93eb302b7fbe0bd9b78c34',
    messagingSenderId: '721822016477',
    projectId: 'mobile-ai-distribution',
    storageBucket: 'mobile-ai-distribution.firebasestorage.app',
    iosBundleId: 'com.danemadsen.maid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5c7-uyIcP9V_Em29heke4cLBTqA-56XE',
    appId: '1:721822016477:ios:93eb302b7fbe0bd9b78c34',
    messagingSenderId: '721822016477',
    projectId: 'mobile-ai-distribution',
    storageBucket: 'mobile-ai-distribution.firebasestorage.app',
    iosBundleId: 'com.danemadsen.maid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuj3iW2uEmkbIyjboZQXLkOrYtZEoZ50M',
    appId: '1:721822016477:web:593b2a6d6ff48831b78c34',
    messagingSenderId: '721822016477',
    projectId: 'mobile-ai-distribution',
    authDomain: 'mobile-ai-distribution.firebaseapp.com',
    storageBucket: 'mobile-ai-distribution.firebasestorage.app',
    measurementId: 'G-P7Q8HH32QV',
  );
}
